#OPCUA CLIENT CONFIGURATIONS
opcUaClient:
  clientId: "cg_opcua_client"
  serverAddress: "opc.tcp://172.24.50.10:4840"
  pollInterval: 10
  maxAge: 2000
#MQTT CLIENT CONFIGURATIONS
clientPub:
  clientId: "cg_opcua_publisher"
  serverAddress: "tcp://test.mosquitto.org:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCAPath: "./certs/pub/xxxxxxxx"
  clientKeyPath: "./certs/pub/xxxxxxxx"
  privateKeyPath: "./certs/pub/xxxxxxxx"
  insecureSkipVerify: true

#LOGS
logs:
  debug: true
  warning: true
  error: true
  critical: true

#MQTT TOPIC TO PUBLISH TO
topicsPub:
  topic:
    - "cg-opcua-publisher/signals"

#OPCUA NODES TO READ
nodesToRead:
  nodes:
    - 
        name: "DigitalValue1"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue1"
    - 
        name: "DigitalValue2"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue2"
    - 
        name: "DigitalValue3"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue3"
    - 
        name: "DigitalValue4"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue4"
    - 
        name: "DigitalValue5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue5"
    - 
        name: "DigitalValue6"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue6"
    - 
        name: "DigitalValue7"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue7"
    - 
        name: "DigitalValue8"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue8"
    - 
        name: "DigitalValue9"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue9"
    - 
        name: "DigitalValue10"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue10"
    - 
        name: "DigitalValue11"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue11"
    - 
        name: "DigitalValue12"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue12"
    - 
        name: "DigitalValue13"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue13"
    - 
        name: "DigitalValue14"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue14"
    - 
        name: "DigitalValue15"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue15"
    - 
        name: "DigitalValue16"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue16"
    - 
        name: "DigitalValue17"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue17"
    - 
        name: "DigitalValue18"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue18"
    - 
        name: "DigitalValue19"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue19"
    - 
        name: "DigitalValue20"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue20"
    - 
        name: "DigitalValue21"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue21"
    - 
        name: "DigitalValue22"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue22"
    - 
        name: "DigitalValue23"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue23"
    - 
        name: "DigitalValue24"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue24"
    - 
        name: "DigitalValue25"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue25"
    - 
        name: "DigitalValue26"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue26"
    - 
        name: "DigitalValue27"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue27"
    - 
        name: "DigitalValue28"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue28"
    - 
        name: "DigitalValue29"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue29"
    - 
        name: "DigitalValue30"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.DigitalValue30"
    - 
        name: "AnaloglValue1"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue1"
    - 
        name: "AnalogValue2"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue2"
    - 
        name: "AnalogValue3"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue3"
    - 
        name: "AnalogValue4"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue4"
    - 
        name: "AnalogValue5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue5"
    - 
        name: "AnalogValue6"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue6"
    - 
        name: "AnalogValue7"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue7"
    - 
        name: "AnalogValue8"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue8"
    - 
        name: "AnalogValue9"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue9"
    - 
        name: "AnalogValue10"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue10"
    - 
        name: "AnalogValue11"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue11"
    - 
        name: "AnalogValue12"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue12"
    - 
        name: "AnalogValue13"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue13"
    - 
        name: "AnalogValue14"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue14"
    - 
        name: "AnalogValue15"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue15"
    - 
        name: "AnalogValue16"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue16"
    - 
        name: "AnalogValue17"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue17"
    - 
        name: "AnalogValue18"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue18"
    - 
        name: "AnalogValue19"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue19"
    - 
        name: "AnalogValue20"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue20"
    - 
        name: "AnalogValue21"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue21"
    - 
        name: "AnalogValue22"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue22"
    - 
        name: "AnalogValue23"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue23"
    - 
        name: "AnalogValue24"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue24"
    - 
        name: "AnalogValue25"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue25"
    - 
        name: "AnalogValue26"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue26"
    - 
        name: "AnalogValue27"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue27"
    - 
        name: "AnalogValue28"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue28"
    - 
        name: "AnalogValue29"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue29"
    - 
        name: "AnalogValue30"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.OnCumulus.AnalogValue30"